### ISSUE TITLE
Bar Screen: Background Wallpaper

### ISSUE THREAD

**Issue by astefancic** [GeorgeCrecoukias/Trivia#64]
I was thinking we could try this for a background. I dont think this background works for the mobile screen, but for the bar background it could to replace the solid colour.
I think something that starts a dark blue at the top and goes lighter.
![Uploading spanish-sky.jpg . . .]()

**Comment by GeorgeCrecoukias** [comment]
closing this, rotating the colours we can talk in a different "issue"
